import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyAk7gscNaKVRV80pvbDya-9qOK52XjQvQM"

import dspy
import warnings
from vanna_agent import get_vanna
from app import clean_sql

warnings.filterwarnings("ignore")


# =========================
# 🔧 DSPy SETUP
# =========================
#lm = dspy.LM(
#    model="gemma-4-31b-it", 
#    provider="google"           
#)

#dspy.settings.configure(lm=lm)
# ========================
# 🧠 DSPy SETUP
# ========================
lm = dspy.LM(
    model="gemini/gemini-flash-latest",      
    api_key=os.environ["GOOGLE_API_KEY"],  
    temperature=0.0,                       
    max_tokens=1000,
)
dspy.configure(lm=lm)

# =========================
# 🧠 DSPy SIGNATURE
# =========================
class SQLTask(dspy.Signature):
    """Generate SQL from natural language"""
    question = dspy.InputField()
    schema = dspy.InputField()
    sql = dspy.OutputField()


# =========================
# 🧠 DSPy MODULES
# =========================
class DSPyContext(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate = dspy.Predict(SQLTask)

    def forward(self, question, schema):
        return self.generate(question=question, schema=schema)


class DSPyReAct(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate = dspy.ChainOfThought(SQLTask)

    def forward(self, question, schema):
        return self.generate(question=question, schema=schema)


# =========================
# 🧪 RUN SQL
# =========================
def run_query(vn, sql):
    try:
        sql = clean_sql(sql)
        return vn.run_sql(sql)
    except Exception as e:
        return str(e)


# =========================
# 🟡 CONTEXT (NORMAL)
# =========================
def context_engineering_sql(question, vn):
    prompt = f"""
You are a SQLite expert.

Tables:
customers(customer_id, name, country, signup_date)
products(product_id, name, category, unit_price)
orders(order_id, customer_id, product_id, quantity, order_date)

Rules:
- Return ONLY SQL
- Do NOT invent tables
- Use LOWER() for string comparisons

Question:
{question}
"""
    response = vn.chat_model.generate_content(prompt)
    return response.text.strip()


# =========================
# 🔵 REACT (NORMAL)
# =========================
def react_sql(question, vn):
    prompt = f"""
You are a SQLite expert using ReAct reasoning.

STRICT RULES:
- Use ONLY schema
- Return ONLY SQL
- Use LOWER() for comparisons

Schema:
customers(customer_id, name, country, signup_date)
products(product_id, name, category, unit_price)
orders(order_id, customer_id, product_id, quantity, order_date)

Question: {question}

Thought:
- Identify tables
- Identify joins
- Identify columns

Action:
Generate SQL
"""
    response = vn.chat_model.generate_content(prompt)
    text = response.text.strip()

    # clean output
    if "SELECT" in text:
        return "SELECT " + text.split("SELECT", 1)[1]
    return text


# =========================
# 🟡 CONTEXT (DSPy)
# =========================
def run_context_dspy(question, vn):
    try:
        schema = """
customers(customer_id, name, country, signup_date)
products(product_id, name, category, unit_price)
orders(order_id, customer_id, product_id, quantity, order_date)
"""
        model = DSPyContext()
        response = model(question=question, schema=schema)

        sql = response.sql.strip()
        result = run_query(vn, sql)

        return sql, result

    except Exception as e:
        return "ERROR", str(e)


# =========================
# 🔵 REACT (DSPy)
# =========================
def run_react_dspy(question, vn):
    try:
        schema = """
customers(customer_id, name, country, signup_date)
products(product_id, name, category, unit_price)
orders(order_id, customer_id, product_id, quantity, order_date)
"""

        model = DSPyReAct()
        response = model(question=question, schema=schema)

        print("\n[DEBUG DSPy RAW]:", response)

        sql = None

        if response:
            if hasattr(response, "sql") and response.sql:
                sql = response.sql.strip()
            elif isinstance(response, dict) and "sql" in response:
                sql = response["sql"].strip()
            else:
                text = str(response)
                if "SELECT" in text:
                    sql = "SELECT " + text.split("SELECT", 1)[1]

        if not sql:
            return "ERROR", "No SQL generated by DSPy"

        # clean formatting
        sql = sql.replace("```sql", "").replace("```", "").strip()

        result = run_query(vn, sql)

        return sql, result

    except Exception as e:
        return "ERROR", str(e)


# =========================
# 🎯 MAIN COMPARISON
# =========================
def compare(question: str):
    vn = get_vanna()

    # NORMAL METHODS
    ce_sql = context_engineering_sql(question, vn)
    ce_result = run_query(vn, ce_sql)

    react_q = react_sql(question, vn)
    react_result = run_query(vn, react_q)

    # DSPy METHODS
    ce_dspy_sql, ce_dspy_result = run_context_dspy(question, vn)
    react_dspy_sql, react_dspy_result = run_react_dspy(question, vn)

    print("\n====================================")
    print("QUESTION:", question)

    print("\n--- Context (Normal) ---")
    print(ce_sql)
    print(ce_result)

    print("\n--- Context (DSPy) ---")
    print(ce_dspy_sql)
    print(ce_dspy_result)

    print("\n--- ReAct (Normal) ---")
    print(react_q)
    print(react_result)

    print("\n--- ReAct (DSPy) ---")
    print(react_dspy_sql)
    print(react_dspy_result)

    print("====================================\n")


# =========================
# ▶️ RUN
# =========================
if __name__ == "__main__":
    q = input("Enter your question: ")
    compare(q)